"""initial_migration

Revision ID: 19f692ecd015
Revises: 
Create Date: 2026-01-04 10:46:12.011970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f692ecd015'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('pipeline_runs_run_id_key'), 'pipeline_runs', type_='unique')
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_run_statistics_id'), 'run_statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_statistics_id'), table_name='run_statistics')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.create_unique_constraint(op.f('pipeline_runs_run_id_key'), 'pipeline_runs', ['run_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
