"""add_topic_modelling

Revision ID: 3c5e2a88f9dd
Revises: 19f692ecd015
Create Date: 2026-01-04 13:10:42.376258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5e2a88f9dd'
down_revision: Union[str, Sequence[str], None] = '19f692ecd015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_modelling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_modelling_id'), 'topic_modelling', ['id'], unique=False)
    # op.drop_constraint(op.f('pipeline_runs_run_id_key'), 'pipeline_runs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('pipeline_runs_run_id_key'), 'pipeline_runs', ['run_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_topic_modelling_id'), table_name='topic_modelling')
    op.drop_table('topic_modelling')
    # ### end Alembic commands ###
