"""add_entity_framing_table

Revision ID: 4a1c7f631765
Revises: 7f3fde1c1818
Create Date: 2026-01-07 13:51:05.898344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1c7f631765'
down_revision: Union[str, Sequence[str], None] = '7f3fde1c1818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_framing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entity_word', sa.String(length=255), nullable=False),
    sa.Column('framing_phrase', sa.String(length=255), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_framing_entity_word'), 'entity_framing', ['entity_word'], unique=False)
    op.create_index(op.f('ix_entity_framing_id'), 'entity_framing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_framing_id'), table_name='entity_framing')
    op.drop_index(op.f('ix_entity_framing_entity_word'), table_name='entity_framing')
    op.drop_table('entity_framing')
    # ### end Alembic commands ###
