"""Refactor signal tables

Revision ID: 7f3fde1c1818
Revises: e67911d7f655
Create Date: 2026-01-05 11:34:37.755666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f3fde1c1818'
down_revision: Union[str, Sequence[str], None] = 'e67911d7f655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Truncate tables to allow adding non-nullable columns without default values
    op.execute("DELETE FROM named_entity_recognition")
    op.execute("DELETE FROM sentiment_analysis")
    op.execute("DELETE FROM topic_modelling")
    
    op.add_column('named_entity_recognition', sa.Column('entity_group', sa.String(length=50), nullable=False))
    op.add_column('named_entity_recognition', sa.Column('word', sa.String(length=255), nullable=False))
    op.add_column('named_entity_recognition', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('named_entity_recognition', sa.Column('start_char', sa.Integer(), nullable=True))
    op.add_column('named_entity_recognition', sa.Column('end_char', sa.Integer(), nullable=True))
    op.drop_column('named_entity_recognition', 'output')
    op.add_column('sentiment_analysis', sa.Column('polarity', sa.Float(), nullable=False))
    op.add_column('sentiment_analysis', sa.Column('label', sa.String(length=20), nullable=False))
    op.add_column('sentiment_analysis', sa.Column('score', sa.Float(), nullable=False))
    op.drop_column('sentiment_analysis', 'output')
    op.add_column('topic_modelling', sa.Column('topic_index', sa.Integer(), nullable=False))
    op.add_column('topic_modelling', sa.Column('keywords', sa.Text(), nullable=False))
    op.drop_column('topic_modelling', 'output')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_modelling', sa.Column('output', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('topic_modelling', 'keywords')
    op.drop_column('topic_modelling', 'topic_index')
    op.add_column('sentiment_analysis', sa.Column('output', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('sentiment_analysis', 'score')
    op.drop_column('sentiment_analysis', 'label')
    op.drop_column('sentiment_analysis', 'polarity')
    op.add_column('named_entity_recognition', sa.Column('output', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('named_entity_recognition', 'end_char')
    op.drop_column('named_entity_recognition', 'start_char')
    op.drop_column('named_entity_recognition', 'score')
    op.drop_column('named_entity_recognition', 'word')
    op.drop_column('named_entity_recognition', 'entity_group')
    # ### end Alembic commands ###
