"""remove topic modelling

Revision ID: 9ea98da020ff
Revises: 4a1c7f631765
Create Date: 2026-01-14 11:57:36.649628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ea98da020ff'
down_revision: Union[str, Sequence[str], None] = '4a1c7f631765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_modelling_id'), table_name='topic_modelling')
    op.drop_table('topic_modelling')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_modelling',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('method_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('topic_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('topic_modelling_article_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_modelling_pkey'))
    )
    op.create_index(op.f('ix_topic_modelling_id'), 'topic_modelling', ['id'], unique=False)
    # ### end Alembic commands ###
